In [94]:
import pandas as pd
import numpy as np

In [95]:
qdf=pd.read_csv("query_dataset.csv")
qdf

query                     tag
0                      Are you open at 10 in morning?                  timing
1                              What are your timings?                  timing
2               On which day you are close in a week?                  timing
3        Till when you are open for service in night?                  timing
4      Are you provide delivery in Indira Nagar area?                delivery
5           How far you provide delivery of an order?                delivery
6            How much atmost I will recieve my order?                delivery
7   Does Dominos deliver the pizza for free after ...                delivery
8                       Is there any offer available?                  offers
9                               What are the offers ?                  offers
10                              What is your address?                 address
11                         How can I reach your shop?                 address
12            In which area I can directly reach you?                 address
13                   Where your pizza shop available?                 address
14             Is there any shop in Polytechnic area?                 address
15                Is there any combo offer available?                   combo
16                         What are the combo offers?                   combo
17   Could you please tell the combo offers avilable?                   combo
18  Is there any combo offer in which i will get 2...                   combo
19                                 What is your menu?                    menu
20                               Can i see your menu?                    menu
21    Margreta pizza avilable available in your shop?                    menu
22          Is there any special day offer available?  special day(wednesday)
23  On which day of week customer will get some di...  special day(wednesday)
24       How much discount i will get on special day?  special day(wednesday)
25                    what is combo offer of the week                   combo
26   Chicken variety of pizza available in your menu?                    menu
27                             available combo offers                   combo
28      what is the basic distance for free delivery?                delivery
29                  how far can you deliver for free?                delivery
30                        is free delivery available?                delivery
31                               what is in the menu?                    menu
32                   what are the options in the menu                    menu
33                                   show me the menu                    menu
34                                 is there any offer                  offers
35                   what are the offers on the pizza                  offers
36                     are discount offers available?                  offers
37                                 when do you close?                  timing
38                                  when do you open?                  timing
39                              what is closing time?                  timing
40                                   how do we reach?                 address
41                      are you available in lucknow?                 address
42                             where are you located?                 address
43                                are you open at 9am                  timing
44                          is there any pizza combos                   combo
45                    what is combo offer of the week                   combo
46                             available combo offers                   combo
47                       are there burgers available?                    menu
48                       do you deliver free of cost?                delivery

In [96]:
x=qdf["query"].tolist()
x

['Are you open at 10 in morning?',
 'What are your timings?',
 'On which day you are close in a week?',
 'Till when you are open for service in night?',
 'Are you provide delivery in Indira Nagar area?',
 'How far you provide delivery of an order?',
 'How much atmost I will recieve my order?',
 'Does Dominos deliver the pizza for free after thirty minutes?',
 'Is there any offer available?',
 'What are the offers ?',
 'What is your address?',
 'How can I reach your shop?',
 'In which area I can directly reach you?',
 'Where your pizza shop available?',
 'Is there any shop in Polytechnic area?',
 'Is there any combo offer available?',
 'What are the combo offers?',
 'Could you please tell the combo offers avilable?',
 'Is there any combo offer in which i will get 2 coke with pizza?',
 'What is your menu?',
 'Can i see your menu?',
 'Margreta pizza avilable available in your shop?',
 'Is there any special day offer available?',
 'On which day of week customer will get some discount?',
 '

In [97]:
y=qdf["tag"].tolist()
y

['timing',
 'timing',
 'timing',
 'timing',
 'delivery',
 'delivery',
 'delivery',
 'delivery',
 'offers',
 'offers',
 'address',
 'address',
 'address',
 'address',
 'address',
 'combo',
 'combo',
 'combo',
 'combo',
 'menu',
 'menu',
 'menu',
 'special day(wednesday)',
 'special day(wednesday)',
 'special day(wednesday)',
 'combo',
 'menu',
 'combo',
 'delivery',
 'delivery',
 'delivery',
 'menu',
 'menu',
 'menu',
 'offers',
 'offers',
 'offers',
 'timing',
 'timing',
 'timing',
 'address',
 'address',
 'address',
 'timing',
 'combo',
 'combo',
 'combo',
 'menu',
 'delivery']

In [98]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer(stop_words="english")
x=vectorizer.fit_transform(x)
x.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [99]:
print(vectorizer.get_feature_names())

['10', '9am', 'address', 'area', 'atmost', 'available', 'avilable', 'basic', 'burgers', 'chicken', 'close', 'closing', 'coke', 'combo', 'combos', 'cost', 'customer', 'day', 'deliver', 'delivery', 'directly', 'discount', 'distance', 'does', 'dominos', 'far', 'free', 'indira', 'located', 'lucknow', 'margreta', 'menu', 'minutes', 'morning', 'nagar', 'night', 'offer', 'offers', 'open', 'options', 'order', 'pizza', 'polytechnic', 'provide', 'reach', 'recieve', 'service', 'shop', 'special', 'tell', 'thirty', 'till', 'time', 'timings', 'variety', 'week']


In [100]:
from sklearn.preprocessing import LabelBinarizer

lb=LabelBinarizer()
y=lb.fit_transform(y)
y

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0,

In [101]:
print(lb.classes_)

['address' 'combo' 'delivery' 'menu' 'offers' 'special day(wednesday)'
 'timing']


In [102]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(random_state=1)
model.fit(x,y)
text = 'Is there any special day offer available?'
input_data = vectorizer.transform([text])
input_data.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [103]:
result=model.predict(input_data)

In [104]:
lb.inverse_transform(result)

array(['special day(wednesday)'], dtype='<U22')

In [105]:
text = 'How can I reach your shop?'
input_data = vectorizer.transform([text])
input_data.toarray()
result=model.predict(input_data)
lb.inverse_transform(result)

array(['address'], dtype='<U22')

In [106]:
text  = 'Chicken variety of pizza available in your menu?'
input_data = vectorizer.transform([text])
input_data.toarray()
result = model.predict(input_data)
ai_tag = (lb.inverse_transform(result))[0]

## Getting Bot Reply

In [107]:
rdf=pd.read_csv("bot_response_dataset.csv")
result_df=rdf[rdf['tag']==ai_tag]
responses=result_df.bot_response.tolist()

In [108]:
import random 
import pickle as pkl

In [109]:
random.choices(responses)

['Mexican Pizza, Cheese Margerita, Chicken nuggets only']

In [110]:
model_data={
    'binarizer':lb,
    'model':model,
    'vectorizer':vectorizer,
    'classes':lb.classes_
}

In [111]:
with open('model.pkl','wb') as f:
    pkl.dump(model_data,f)

## Testing saved model

In [112]:
model_loaded_data={}
with open('model.pkl','rb') as f:
    model_loaded_data=pkl.loads(f.read())

In [113]:
def predict_tag(txt="Hello World",binarizer=None,model=None,vectorizer=None,*args,**kwargs):
    input_vector=vectorizer.transform([txt])
    result=model.predict(input_vector)
    output_tag=lb.inverse_transform(result)
    return output_tag[0]

In [114]:
def get_bot_reply(predicted_tag):
    result_df=rdf[rdf['tag']==predicted_tag]
    responses=result_df.bot_response.to_list()
    return random.choice(responses)

In [115]:
text = 'Is there any offer available?'
tag = predict_tag(text,**model_loaded_data)
get_bot_reply(tag)

'-> 10% discount on 2 pizzas, -> 30% discount on chiken nuggets\t'